version: '2'

services:
  db:
    image: 'postgres:13'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env_docker'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  redis:
    image: 'redis:7-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    platform: linux/x86_64
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/chat_app'
    env_file:
      - '.env_docker'

  app:
    platform: linux/x86_64
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - '3000:3000'
    volumes:
      - '.:/chat_app'
    env_file:
      - '.env_docker'

volumes:
  redis:
  postgres: